global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus_master"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'nginx_status'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.10.10.50:9113']
